version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: etl-wizard
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ~/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
